### ISSUE TITLE
Mozo ne se lance pas car il faut python2-gobject.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/mate#10]
Si on essaye de lancer Mozo (alias Menu Principal), celui-ci ne se lance pas.

Si on passe par la ligne de commande, voici la sortie : 

`fred [ ~ ]$ Traceback (most recent call last):`
`File "/usr/bin/mozo", line 22, in <module>`
`from Mozo.MainWindow import MainWindow`
`File "/usr/lib/python2.7/site-packages/Mozo/MainWindow.py", line 20, in <module>`
`import gi`
`ImportError: No module named gi`

`[1]+  Exit 1                  mozo`

Le paquet python2-gobject est indispensable pour lancer le logiciel. Une dépendance à rajouter à Mate-extra, non ?

J'ai dû l'installer à la main pour pouvoir lancer Mozo :(

**Comment by tnut** [comment]
merci pour ce retour, je corrige

**Comment by FredBezies** [comment]
De rien.

**Comment by FredBezies** [comment]
Et **bip**

Mozo refuse toujours de se lancer... :(

Toujours la même erreur. J'ai réinstallé le paquet python2-gobject, mozo refuse toujours de se lancer :(

![mozo](https://cloud.githubusercontent.com/assets/8571419/16893989/dbe5ba58-4b48-11e6-9e42-68754c072a49.png)

**Comment by tnut** [comment]
get python-gobject

**Comment by FredBezies** [comment]
Méchants paquets dont les noms sont proches :D

**Comment by FredBezies** [comment]
Je confirme que le bug est corrigé avec mozo-1.14.0-3. Merci !

**Comment by FredBezies** [comment]
De retour sous NuTyX 8.2.93... Soupir... Je réouvre le bug, désolé :(

**Comment by tnut** [comment]
Ah oui bien vu, je corrige ça,  je tiens le bug au chaud. Y a de toute
façons pas mal d'autres soucis

2017-01-15 19:32 GMT+01:00 FredBezies <notifications@github.com>:

**Comment by FredBezies** [comment]
C'est le bug qui m'a sauté aux yeux en premier... Car le plus visible !

**Comment by tnut** [comment]
Fixed

**Comment by FredBezies** [comment]
Merci :D
