### ISSUE TITLE
Weather applet is broken in libmateweather 1.14.0 ; fixed in 1.14.1/1.14.2.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/mate#12]
You have to rebuild libmateweather against version 1.14.1 or 1.14.2

See this commit : https://github.com/mate-desktop/libmateweather/commit/835055e0d0b950d3f66ad236de7e40942f6f7d8e

If you don't rebuild libmateweather, both weather applet and weather icon in date display are broken.

**Comment by tnut** [comment]
Thanks for your feedback. I see a lot of other mate packages that need to be updated. Will commit them all

**Comment by FredBezies** [comment]
Fixed. Closing bug ;)
