### ISSUE TITLE
[souhait] Paquet à rajouter : sound-theme-freedesktop

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/mate#13]
C'est un souhait, mais ce serait bien de rajouter sound-theme-freedesktop à l'installation de Mate. Pour avoir les alertes sonores, du moins, pouvoir les activer pour les utilisateurs intéressés.

**Comment by tnut** [comment]
c est donc une dep runtime. Mate n 'étant pas un paquet mais une collection, il faut identifier l'apli qui utilise cette dep runtime

**Comment by FredBezies** [comment]
Je pense que c'est libcanberra. Du moins si j'en crois les dépendances pour Archlinux :)

**Comment by tnut** [comment]
pas cool ça, je crois qu'un article " comment installer mate" (et toute
autre interfaces graphiques) avec et sans extras serai le mieux.

2016-10-09 10:44 GMT+02:00 FredBezies <notifications@github.com>:

**Comment by tnut** [comment]
Merci pour l'info que je tiens au chaud.

**Comment by tnut** [comment]
Ne sera pas ajouter, la philosophie de NuTyX étant flexibilitée. Laissons le choix à l'utilisateur.
