### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by jaycenet** [NuTyX/mate#17]
Bonjour,

Une fois que toutes les étapes de construction ont été effectuées, comment installe t'on les paquets en dehors du chroot sur #NuTyX ?

Je vous remercie

**Comment by tnut** [comment]
SI tu as une chroot qui est sur  la même branche que ta NuTyX principale, c'est très simple. Tu ajoutes les 2 dossiers où se trouvent tes binaires fraîchement compilés dans le fichier de configuration de cards de ta NuTyX principale. Voici un exemple de dossiers :

- La chroot est dans /mnt/hd (c'est le dossier par défaut)
- Les collections mate et mate-extra sont dans /usr/ports/mate et /usr/ports/mate-extra de ta chroot, ils sont donc accéssibles depuis ta principale dans:
 /mnt/hd/usr/ports/mate et  /mnt/hd/usr/ports/mate-extra

Tu ajoutes donc en début de fichier dans /etc/cards.conf de ta NuTyX principale:

dir  /mnt/hd/usr/ports/mate
dir  /mnt/hd/usr/ports/mate-extra

Et si tu as configuré correctement le fichier /etc/pkgmk.conf de ta chroot, tes binaires fraîchement compilés ds ta chroot seront directement visible et installable dans ta principale

cards info -b pluma (pour avoir les infos du binaire)
ou 
cards info -p pluma (pour avoir les infos du port)

La prochaine vidéo sur Youtube (j'espère ce we) va expliquer tout cela en détail. 

Bonne chance.

**Comment by tnut** [comment]
https://youtu.be/ikCnargpuAs

**Comment by jaycenet** [comment]
Ok merci ça fonctionne

**Comment by tnut** [comment]
Super

2017-04-28 20:28 GMT+02:00 Jayce <notifications@github.com>:
