### ISSUE TITLE
mate-system-monitor & gtkmm3.

### ISSUE THREAD

**Issue by sh4d0w31410** [NuTyX/mate#8]
mate-system-monitor requiert gtkmm3, mais le paquet appartient à la collection gnome.

**Comment by tnut** [comment]
c'est embêtant ça, faut que je regarde

**Comment by tnut** [comment]
gtkmm3 est aussi dans gui (là où il doit être)

**Comment by sh4d0w31410** [comment]
Impeccable alors, je ferme.
