### ISSUE TITLE
Mate themes doit rajouter le paquet murrine

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/mate#9]
Salut.

Un petit rapport de bug au passage. J'ai installé Mate sur la NuTyX 8.2 beta1. Si le paquet murrine n'est pas installé, le thème par défaut est un peu cassé.

Un "get murrine"  suivi d'une déconnexion et d'une reconnexion corrige le problème :)

**Comment by tnut** [comment]
je regarderai

**Comment by FredBezies** [comment]
Une capture d'écran avec le panneau de préférences qui se plaint de l'absence de murrine.

![mate-themes-murrine-absent](https://cloud.githubusercontent.com/assets/8571419/16845499/6a4b4af8-49e9-11e6-83df-89b2881001b3.png)

**Comment by tnut** [comment]
J'e m'en occupe, murrine doit être déplacée pour que mate puisse en profier

**Comment by FredBezies** [comment]
Je viens de vérifier à l'instant. C'est corrigé ! Merci !
